# Site settings
title: Espresso
description: > # this means to ignore newlines until "baseurl:"
  Espresso - The expressive, flexible testing and assertion library for the
  Iodine programming language.
baseurl: "/espresso"
github_username:  IodineLang

# Build settings
markdown: kramdown
